export const ONE_HOUR_MILLISECONDS = 3600000;
export const ONE_MINUTE_MILLISECONDS = 60000;
export const ONE_SECOND_MILLISECONDS = 1000;

export const MILLIS = {
  hour: ONE_HOUR_MILLISECONDS,
  minute: ONE_MINUTE_MILLISECONDS,
  second: ONE_SECOND_MILLISECONDS,
};
